### ISSUE TITLE
topic addition for better community reach

### ISSUE THREAD

**Issue by Wladefant** [raddad772/jsmoo#20]
Hey,
for better reach of the community, I would like to suggest to add the following topic to the repository: `motorola-68000`

[How to do this](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics#adding-topics-to-your-repository)

**Comment by raddad772** [comment]
thanks, I never finished my m68k core though, and don't plan to in this iteration of the emulators (I am currently porting them to C11 in a library style for easy binding to other languages). Thanks!
