### ISSUE TITLE
Flags not correct for opcode 0xED 0xB3

### ISSUE THREAD

**Issue by friol** [raddad772/jsmoo#22]
Flags seems wrong for opcode EDB3 (OTIR).
For example, the documentation says that the C flag (the lower bit of f) is unaffected by this instruction, but in the test cases C is changed.

**Comment by raddad772** [comment]
Hm. My core passes zexall, but I don't actually know if that tests OUTI. I'll look into it, thanks
Do be aware of https://zxe.io/depot/documents/Undocumented%20Z80%20Flags%20rev1.0%20%282018-08-21%29%28Banks,%20David%29%28en%29%5B%21%5D.pdf please, but I don't see C modified by OUTI or OTIR there. So I'll check into it

**Comment by raddad772** [comment]
So, The Undocumented Z80 Documented, says

```
And now the for OUTI/OTIR/OUTD/OTDR instructions. Take state of the L after the increment
or decrement of HL; add the value written to the I/O port to; call that k for now. If k > 255,
then the CF and HF flags are set
```

Furthermore, I asked other emulator authors, and they replied that they implemented it this way too.

Thanks for the Issues. Keep them coming, I'd rather some false positives than let through any bad tests!

**Comment by friol** [comment]
I've adapted the flag behaviour to what The Undocumented Z80 says (and corrected C and H flags), but I still think the flags for 0xEDB3 are wrong in the tests. I have the same code for 0xEDA3 (OUTI), and 0xEDA3 passes all the tests.
Thanks.

**Comment by raddad772** [comment]
Yeah, the Undocumented Z80 says IN is different from OUT,but I have the same code used. I need to investigate this a bit deeply.
As a side-note, I'm glad the tests need this level of examination to have an issue. We will end up with super powerful tests!

**Comment by raddad772** [comment]
The current behavior is definitely the most correct understood behavior now, this should be resolved
