### ISSUE TITLE
Z80 - Wrong values of A for opcode tests ED 5F

### ISSUE THREAD

**Issue by friol** [raddad772/jsmoo#24]
Hello,
opcode ED 5F should be simply a copy of register R in A, but from the tests, R and A are incremented...
Thanks

**Comment by raddad772** [comment]
During opcode fetch, the Z80 outputs IR on the address bus to refresh DRAM, and then increments R by 1.

It does this for both the ED and 5F bytes, and does both memory refreshes. Thus, R is incremented by 2 before it is transferred to A.

I verified this in VisualZ80Remix. Running this instruction with IR=0, A=2 afterwards. I also verified that at least the first test reproduces this properly.

Thanks so much for your reports!

**Comment by raddad772** [comment]
Thanks

**Comment by friol** [comment]
Thanks, the existing documentation you find on the web does often overlook those aspects.
