### ISSUE TITLE
Z80 opcodes with 11 cycles instead of 12

### ISSUE THREAD

**Issue by friol** [raddad772/jsmoo#26]
I hope this won't be another false positive.
Some 0xCB prefixed opcodes show 11 cycles instead of 12 in the tests.
For example, 0xCB 0x46.
Thanks

**Comment by raddad772** [comment]
Just pushed a new version with this fixed for the BIT x, (HL) and related opcodes, thanks! Let me know if you find any others

**Comment by friol** [comment]
Finally not a false positive! Thanks!
