### ISSUE TITLE
Z80: flag `C` for `INI` instruction (EDA2) does not seem to be correct

### ISSUE THREAD

**Issue by konstantin-dzreev** [raddad772/jsmoo#31]
In chapter 4.3 "I/O Block Instructions" "The Documented Z80 Undocumented" states that:
```
for IND/INDR: 
        HF and CF Both set if ((HL) + ((C - 1) & 255) > 255)
for INI/INIR:
        HF and CF Both set if ((HL) + ((C + 1) & 255) > 255)
```
The way you do flag `C` for `IND`, matches the book:
```
this.regs.F.C = ((((this.regs.C - 1) & 0xFF) + data) & 0x100) >>> 8;
```
but the way you do it for `INI` does not:
```
this.regs.F.C = +(((this.regs.C + 1) + data) > 0xFF);
```
Is this a bug, or was there a reason to implement it this way?
Thanks!

**Comment by raddad772** [comment]
Hi! Sorry it took so long to get back about this. @redcode helped out and we merged in a PR that should fix literally ANY errors with Z80. these tests now agree with the most accurate-known Z80 emulator (in "NMOS quirks" mode). let me know if you notice anything else!
